### ISSUE TITLE
[BUG] Empty Sources produce an exception, whilst Normal Linq Does not

### ISSUE THREAD

**Issue by Smurf-IV** [jackmott/LinqFaster#14]
Using your .`Where###` APIs on an Empty List or Array causes an exception to be thrown, whilst the Default Linq `.Where` does not.
This means that i have to create lot of wrapper code to deal with
i.e. check for `Any()` before calling your API's 'else' set to `new List<T>()`

This is not the same as passing null, just Empty Arrays or Lists from other calls.

The same Exception applies to your `Select###` API's as well.

**Comment by jackmott** [comment]
Is it an ArgumentOutOfRangeException?

**Comment by jackmott** [comment]
I was able to replicate this with WhereParallel but not others, can you provide some code examples?

I have a fix for all of the Parallel cases.

**Comment by Smurf-IV** [comment]
Just So happens, I found it on the parallel `listComplete.WhereSelectP(`

**Comment by jackmott** [comment]
ok so this is the same bug you noted in the other issue. going to close this.
