### ISSUE TITLE
[Bug/Enhancement] Partitioner parameter value

### ISSUE THREAD

**Issue by Smurf-IV** [jackmott/LinqFaster#16]
[_Enhancement_] I'm trying to "Optimise" the use of parallel processing, so I though that if I pass in a "chunking" value of what I feel will be beneficial to be in a single thread chunk before parallel processing needs to happen (i.e. simple comparison logic for less than 100 values it quicker in a single thread than the overhead of setting up the parallel processing)
I thought the following would be ideal:
`maxGradeCount += filtered.CountP(ft=> ft.Number == maxGrade, 100);`
where `filtered` can contain **0** to some large number values above 10,000.

[**BUG**] What I get is  `Specified argument was out of the range of valid values.` when filtered has 0 elements. This **does not** occur when I use `CountF`

**Comment by Smurf-IV** [comment]
[Question] Does this bug also apply to the other Parallel API's ? e.g. `MaxP`

**Comment by jackmott** [comment]
Good find, I'll fix this.

**Comment by jackmott** [comment]
I have a fix for this, will close this once it is packaged up and nuget is updated.

**Comment by Smurf-IV** [comment]
> I have a fix for this, will close this once it is packaged up and nuget is updated.

Is it the Bug fix, and / or the chunking idea ?

**Comment by jackmott** [comment]
I fixed the bug for filtered elements being 0.
I think what you are wanting for chunksize already exists? There is an optional parameter on all of the parallel methods for batchSize.

**Comment by jackmott** [comment]
I've pushed the fix up to github and nuget, it should show up on nuget soon as version 1.0.2 for the Parallel libs.  Closing this.
