### ISSUE TITLE
[Enhancement] SumS (etc) to work on List<T> please

### ISSUE THREAD

**Issue by Smurf-IV** [jackmott/LinqFaster#19]

**Comment by jackmott** [comment]
it isn’t possible without extremely unsafe code. to expand on this, you can get at the array inside of the List<T> using some hacks, but it isn't guaranteed to work on all implementations of .NET, or future implementations.  If you really need growable array behavior with simd features, best thing to do is just copy the source to List<T>, and make the array public.

**Comment by Smurf-IV** [comment]
Duplicate of #15
