### ISSUE TITLE
loop type

### ISSUE THREAD

**Issue by jnyrup** [jackmott/LinqFaster#5]
The extension methods in e.g. `Sum.cs` uses foreach for arrays and C-style loops for Lists, just as the [benchmarks](https://www.infoq.com/articles/For-Each-Performance) tells us.
Others such as `Min.cs` does not follow this practice.

For C-style loops a quick grep finds 101 occurrences with Lists and 122 occurrences for arrays.

**Comment by jackmott** [comment]
`foreach` performs identically on arrays, so it is ok to use there.

In `Min.cs`, some of the loops don't start at 0 so we can't use foreach.

Are you seeing any cases where there would be a performance impact or just looking for consistency of style?

**Comment by jnyrup** [comment]
As the library seems quite focused on performance, I searched for places for even the slightest gain and the article does mention a .1 µs difference for using `foreach` vs C-style loops for arrays.

There are 45 occurrences of `for (int i = 0; i < source.Length; i++)` and for a few samples, the index wasn't used.
E.g in [Min.cs]( https://github.com/jackmott/LinqFaster/blob/54307ebc7e27fb637a12351a18bf5bb55f7a6c82/LinqFaster/Min.cs#L109)

I haven't done any benchmarks to test the actual difference, and if you prefer to avoid switching loop types to much, that's no problem.

**Comment by jackmott** [comment]
I'll check the compiled IL of each in a little bit to confirm or deny if there is really a difference in how it compiles.  The 1us difference may just be noise. I'll find out. Thanks.

**Comment by jackmott** [comment]
I've double checked and confirmed that foreach and for loops perform the same with arrays, at least under RyuJIT.  I can check and confirm if this is true under mono as well.

**Comment by jnyrup** [comment]
You shouldn't do it for my sake. 
I'm convinced.
